# Generated by Django 5.0.6 on 2024-07-07 22:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldvalue',
            name='field_type',
        ),
        migrations.RemoveField(
            model_name='fieldvalue',
            name='inventory',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='CellConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('cell_type', models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('TASK_COMPLETED', 'Task Completed'), ('DISPLAY_BOX', 'Display Box')], max_length=20)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_configurations', to='inventory.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='inventory.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('value_boolean', models.BooleanField(default=False)),
                ('value_datetime', models.DateTimeField(blank=True, null=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.cellconfiguration')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='inventory.inventoryelement')),
            ],
        ),
        migrations.DeleteModel(
            name='FieldType',
        ),
        migrations.DeleteModel(
            name='FieldValue',
        ),
    ]
